#!/usr/bin/perl
#

#
# See if the first argument is '-I' which specifies an include path
# for the TestLib module
#
$ctr=0;
if ($ARGV[0] eq "-I") {
   unshift @INC, $ARGV[1];
   $ENV{'PATH'} = $ENV{'PATH'} . ":.:" . $ARGV[1];
   $ctr = 2;
   }
#
# See if the TESTLIBDIR environmental variable is set, which provides
# an include path for the TestLib module
#
$pwd = `pwd`;
chomp($pwd);
if ($ENV{TESTLIBDIR} ne "") {
   $tmp = $ENV{TESTLIBDIR};
   @words = split /[ ]+/, $tmp, $#tmp;
   foreach $word (@words) {
     unshift @INC, $word;
     }
   }
require TestLib;

#
# Statistics collected by the analyzeData call-back routine
#
$final_seed="ERROR";
$final_status="ERROR";
$final_lpflag=0;
$final_value="ERROR";
$final_rtime="ERROR";
$final_ttime="ERROR";
$final_subproblemscreated="ERROR";
$final_subproblemsbounded="ERROR";
$final_subproblemssplit="ERROR";
$final_subproblemsdead="ERROR";
$final_subproblemsbounding="ERROR";
$final_subproblemssplitting="ERROR";

@trial_seed=();
@trial_lpflag=();
@trial_status=();
@trial_value=();
@trial_rtime=();
@trial_ttime=();
@trial_subcreated=();
@trial_subbounded=();
@trial_subsplit=();
@trial_subdead=();
@trial_subbounding=();
@trial_subsplitting=();

sub update_stats {
  push @trial_seed, $final_seed;
  push @trial_lpflag, $final_lpflag;
  push @trial_status, $final_status;
  push @trial_value, $final_value;
  push @trial_rtime, $final_rtime;
  push @trial_ttime, $final_ttime;
  push @trial_subcreated, $final_subcreated;
  push @trial_subbounded, $final_subbounded;
  push @trial_subsplit, $final_subsplit;
  push @trial_subdead, $final_subdead;
  push @trial_subbounding, $final_subbounding;
  push @trial_subsplitting, $final_subsplitting;
}

#
# A callback routine that is used to analyze an output file generated by
# PEBBL.
#
sub analyzeData {
    $final_seed=0;
    my $filename = @_[0];
    open (INPUT, $filename) || die "cannot open file $filename!";
    while ($line = <INPUT>) {
      chomp($line);
      @word = split /[ \t]+/, $line, $#line;
      if ($#word > 0) {
         #print "HERE $#word\n";
         if ($word[0] eq "") {
            shift @word;
         }
         if (($word[0] eq "No") && ($word[1] eq "integer")) {
            $final_lpflag = 1;
         }
         elsif (($word[0] eq "LP") && ($word[1] eq "value=")) {
            $final_value = eval($word[2]);
         }
         elsif (($word[2] eq "Value") && ($word[3] eq "=")) {
            $final_value = eval($word[4]);
         }
         elsif (($word[0] eq "Problem") && ($word[2] eq "infeasible")) {
            $final_value = 0.0;
         }
         elsif (($word[0] eq "Integer") && ($word[1] eq "Infeasible")) {
            $final_value = 0.0;
         }
         elsif (($word[0] eq "Problem") && ($word[2] eq "unbounded")) {
            $final_value = "Unbounded";
         }
         elsif (($word[0] eq "Total") && ($word[1] eq "Runtime=")) {
            $final_rtime = eval($word[2]);
         }
         elsif (($word[0] eq "Total") && ($word[1] eq "Time=")) {
            $final_ttime = eval($word[2]);
         }
         elsif ($word[0] eq "Created") {
            $final_subproblemscreated = eval($word[1]);
         }
         elsif ($word[0] eq "Bounded") {
            $final_subproblemsbounded = eval($word[1]);
         }
         elsif ($word[0] eq "Split") {
            $final_subproblemssplit = eval($word[1]);
         }
         elsif ($word[0] eq "Dead") {
            $final_subproblemsdead = eval($word[1]);
         }
         elsif (($word[0] eq "Started") && ($word[1] eq "Bounding")) {
            $final_subproblemsbounding = eval($word[2]);
         }
         elsif (($word[0] eq "Started") && ($word[1] eq "Splitting")) {
            $final_subproblemssplitting = eval($word[2]);
         }
      }
    }
  if ($final_value eq "ERROR") {
     @_[1] = "Fail";
  }
  close(INPUT);
  update_stats();
}

$description="  <Description>ERROR</Description>\n";

#
# A callback that is used to print measurement information
#
sub printMeasurements {
     print $description;
     $i = 0;
     while ($i <= $#trial_status) {
       print "  <Trial id=\"$i\" seed=\"$trial_seed[$i]\">\n";

       if ($final_value == "Infeasible") {
          print "     <Value name=\"Value\" type=\"numeric/double\">$final_value</Value>\n";
       } else {
          print "     <Value name=\"Value\" type=\"numeric/double\">$final_value</Value>\n";
       }

       print "     <Value name=\"NormalizedValue\" type=\"numeric/double\">";
       if ($final_value eq "ERROR") {
          print "ERROR";
       } else {
          print ($final_value-$solnvalue+1.0);
       }
       print "</Value>\n";

       print "     <Value name=\"SolverTime\" type=\"numeric/double\">";
       if ($final_rtime eq "ERROR") {
          print "ERROR";
       } else {
          print $final_rtime;
       }
       print "</Value>\n";
  
       print "     <Value name=\"TotalTime\" type=\"numeric/double\">";
       if ($final_ttime eq "ERROR") {
          print "ERROR";
       } else {
          print $final_ttime;
       }
       print "</Value>\n";

       if ($final_lpflag == 0) {
          print "     <Value name=\"SubproblemsCreated\" type=\"numeric/int\">$final_subproblemscreated</Value>\n";
          print "     <Value name=\"SubproblemsBounded\" type=\"numeric/int\">$final_subproblemsbounded</Value>\n";
          print "     <Value name=\"SubproblemsSplit\" type=\"numeric/int\">$final_subproblemssplit</Value>\n";
          print "     <Value name=\"SubproblemsDead\" type=\"numeric/int\">$final_subproblemsdead</Value>\n";
          print "     <Value name=\"SubproblemsBounding\" type=\"numeric/int\">$final_subproblemsbounding</Value>\n";
          print "     <Value name=\"SubproblemsSplitting\" type=\"numeric/int\">$final_subproblemssplitting</Value>\n";
          }
  
     print "  </Trial>\n";
     $i = $i + 1;
   }
}


##
## MAIN ROUTINE
##
if (! @ARGV) {
   print "\n";
   print "exp.pebbl.pl - PEBBL experiment driver (for LP/MILP problems)\n";
   print "\n";
   print "usage:\n";
   print "\n";
   print "   exp.pebbl.pl [options] <expname> <testname> <factor-id> <factor-value> [...]\n";
   print "\n";
   print "options:\n";
   print "\n";
   print "   --knapsack\t\t\tSolve a knapsack problem.\n";
   print "\n";
   print "   --debug\t\tPrint debugging information.\n";
   print "\n";
   print "notes:\n";
   print "\n";
   print "   This script is launched by 'runexp' to execute and process a\n";
   print "   single test from an experiment file.  The output of this test\n";
   print "   is stored in the file <expname>-<testname>.out, which can be\n";
   print "   reviewed after the test is performed.  This script generates an\n";
   print "   XML summary that is included in the <expname>.results.xml file\n";
   print "   by 'runexp'.\n";
   print "\n";
   print "   This script is not intended for interactive use.  Consequently,\n";
   print "   the processing of the command-line options is somewhat fragile.\n";
   print "   For example, it depends on the order in which the options are\n";
   print "   processed in this script!\n";
   print "\n";
   print "   This script assumes that the first factor is the test information,\n";
   print "   and the remaining factors specify command-line options.\n";
   exit;
}
#
# Process command line arguments
#
$testoptions = "";
if ($ARGV[$ctr] eq "--knapsack") {
   $ctr += 1;
   $solver = "knapsackTest";
}
else { $solver = "UNKNOWN_SOLVER"; }
if ($ARGV[$ctr] eq "--debug") {
   $ctr += 1;
   $debug = 1;
}
$description = TestLib::generate_description($ctr,@ARGV);
$expname = $ARGV[$ctr];
$ctr +=1;
$testname = $ARGV[$ctr];
$ctr +=1;
$ntrials = $ARGV[$ctr];
$ctr+=3;
while ($ctr <= $#ARGV) {
  $testoptions .= $ARGV[$ctr] . " ";
  $ctr+=3;
}
if ($debug == 1) {
   print "options: $testoptions\n";
}
#
# Process experiment tag/value pairs
#
# This is a convention that is not explicitly supported by the 
# 'runexp' utility, but this is a convenient way for
# structuring experiment testing.
#
$solnvalue = "unknown";
$tolerance = 1e-12;
$files = "";
%testparams = ();
$auxoptions = TestLib::process_testoptions($testoptions, \%testparams);
if (defined($testparams{"_optimum"})) {
   $solnvalue = $testparams{"_optimum"};
} elsif (defined($testparams{"_value"})) {
   $solnvalue = $testparams{"_value"};
}
foreach $word (TestLib::get_tokens($testparams{"_data"})) {
  $files = $files . $word . " ";
}
if ($debug == 1) {
   print "exp:       $expname\n";
   print "value:     $solnvalue\n";
   print "tolerance: $tolerance\n";
   print "data:      $files\n";
}
   #
   # Setup PEBBL command line
   #
   $cmdline = "$solver ";
   @options = split(/ /,$auxoptions,$#auxoptions);
   while (@options) {
     local $tmp = shift @options;
     if ($tmp ne "") {
        $cmdline .= " --" . $tmp;
     }
   }
   $cmdline .= " " . $files;
if ($debug == 1) {
   print "CMDLINE: $cmdline\n";
}
#
# Launch the test with the TestLib driver.
#
TestLib::run_experiments(\*STDOUT, $expname, $testname, $cmdline, $ntrials, \&analyzeData, \&printMeasurements, $auxoptions, \%testparams);
