/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class anl_teva_db_TSOReader */

#ifndef _Included_anl_teva_db_TSOReader
#define _Included_anl_teva_db_TSOReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     anl_msv_dpf_erd_db_TSOReader
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;CC)I
 */
JNIEXPORT jint JNICALL Java_anl_msv_dpf_erd_db_TSOReader_open
  (JNIEnv *, jobject, jstring, jstring, jchar, jchar);

/*
 * Class:     anl_msv_dpf_erd_db_TSOReader
 * Method:    positionAfterPrologue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_anl_msv_dpf_erd_db_TSOReader_positionAfterPrologue
  (JNIEnv *, jobject, jint);

/*
 * Class:     anl_msv_dpf_erd_db_TSOReader
 * Method:    readPrologue
 * Signature: (I[Ljava/lang/Object;[I)V
 */
JNIEXPORT void JNICALL Java_anl_msv_dpf_erd_db_TSOReader_readPrologue
  (JNIEnv *, jobject, jint, jobjectArray, jintArray);

/*
 * Class:     anl_msv_dpf_erd_db_TSOReader
 * Method:    closeAndFreeMemory
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_anl_msv_dpf_erd_db_TSOReader_closeAndFreeMemory
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     anl_msv_dpf_erd_db_TSOReader
 * Method:    readSimulationResults
 * Signature: (IIII[[F)Z
 */
JNIEXPORT jboolean JNICALL Java_anl_msv_dpf_erd_db_TSOReader_readSimulationResults
  (JNIEnv *, jobject, jint, jint, jint, jint, jobjectArray);

/*
 * Class:     anl_msv_dpf_erd_db_TSOReader
 * Method:    getIndex
 * Signature: (IIII)[Lanl/teva/dp/db/DataIndex
 */
JNIEXPORT jobject JNICALL Java_anl_msv_dpf_erd_db_TSOReader_getIndex
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
