#include <sp/scenario.h>
#include <utilib/exception_mngr.h>
#include "MassConsumedObjective.h"
#include "PopulationExposedObjective.h"
#include "PopulationKilledObjective.h"
#include "NumberFailedDetectionsObjective.h"
#include "TimeToDetectionObjective.h"
#include "VolumeContaminatedWaterConsumedObjective.h"
#include "ExtentOfContaminationObjective.h"
#include "impacts.h"

/// Argument processing for the standalone version
void process_arguments(int argc, char **argv, PNodeInfo&nodes, PLinkInfo&links,
      		       PNetInfo&net, PTSO&tso, PSource&sources,
      		       std::string&outputFilePrefix,
      		       std::string&tsoFileOrDirectoryName,
      		       int&detectionDelay,
      		       double&minQuality,
      		       bool&mcSelected,
      		       bool&vcSelected,
      		       bool&nfdSelected,
      		       bool&tdSelected,
      		       bool&ecSelected,
      		       std::string&epanetInputFilename,
      		       bool&pkSelected,
      		       bool&peSelected,
      		       std::string&taiInputFilename,
      		       std::string&tsoPattern,
      		       std::string&sensorInputFilename,
      		       std::list<int>&sensorLocations)
{
      if(argc<3) {
	std::cerr << "\
\n\
tso2Impact - An application that reads a TSO file and creates one or more\n\
\timpact files that are used to formulate sensor placement problems.\n\
\n\
usage:\n\
\n\
   tso2Impact <output-prefix> <tso-directory-or-file> [options...]\n\
\n\
options:\n\
\n\
   -detectionDelay <minutes>\n\
	This parameter indicates that a delayed detection impact will be\n\
	computed for the specified delay.\n\
\n\
   -minQuality <threshold>\n\
	This parameter indicates the minimum threshold needed to perform\n\
	detection with a sensor.\n\
\n\
   -mc\n\
	If this flag is specified, an impact file wll be generated for the\n\
	'mass consumed' measure.\n\
\n\
   -vc\n\
	If this flag is specified, an impact file wll be generated for the\n\
	'volume consumed' measure.\n\
\n\
   -td\n\
	If this flag is specified, an impact file wll be generated for the\n\
	'time-to-detection' measure.\n\
\n\
   -nfd\n\
	If this flag is specified, an impact file wll be generated for the\n\
	'number-of-failed detections' measure.\n\
\n\
   -ec\n\
	If this flag is specified, an impact file wll be generated for the\n\
	'extent of contamination' measure.\n\
\n\
   -pk <tai-input-file>\n\
	If this parameter is specified, an impact file wll be generated for the\n\
	'population killed' measure.  The TAI input file is a threat_assess\n\
	input that specifies parameters like dosage, response, lethality, etc\n\
	Note: it is an intensive measure to compute.\n\
\n\
   -pe <tai-input-file>\n\
	If this parameter is specified, an impact file wll be generated for the\n\
	'population exposed' measure.  The TAI input file is a threat_assess\n\
	input that specifies parameters like dosage, response, lethality, etc\n\
	This measure concerns the number of people 'sickened' by exposure.\n\
\n\
   -epanetin <file-name>\n\
	This is used for TSO file versions less than 6.0, when computation\n\
	of the 'ec' objective is specified.  Pipelengths are extracted from\n\
	the EPANET input file.\n\
\n\
   -tsoPattern <string>\n\
	This string specifies a regular expression for all input TSO files\n\
	when the files are stored in a directory (e.g. when generated by TEVA).\n\
\n\
arguments:\n\
\n\
   <output-prefix>\n\
	The prefix used for all files generated by tso2Impact.\n\
\n\
   <tso-director-or-file>\n\
	This arguement indicates either a TSO file (generated by threat_sim) or\n\
	a directory name for TSO files (generated by TEVA).  If the later, then\n\
	the filenames must be specified with the -tsoPattern option.\n\
" << std::endl;
	  exit(1);
	}

      ////////////////////////////////////////////////////////
      // parse/proceess any optional command-line arguments //
      ////////////////////////////////////////////////////////

      outputFilePrefix = argv[1];

      tsoFileOrDirectoryName = argv[2];

      int currentArgIndex(3);
      while(currentArgIndex<argc)
	{
	  if(strcmp(argv[currentArgIndex],"-mc")==0) 
	    {
	      mcSelected=true;
	      std::cout << "Generating mass consumed impact file" << std::endl;
	    } 
	  else if(strcmp(argv[currentArgIndex],"-vc")==0) 
	    {
	      vcSelected=true;
	      std::cout << "Generating volume of contaminated water consumed impact file" << std::endl;
	    } 
	  else if(strcmp(argv[currentArgIndex],"-nfd")==0) 
	    {
	      nfdSelected=true;
	      std::cout << "Generating number of failed detections impact file" << std::endl;
	    } 
	  else if(strcmp(argv[currentArgIndex],"-td")==0) 
	    {
	      tdSelected=true;
	      std::cout << "Generating time to detection impact file" << std::endl;
	    } 
	  else if(strcmp(argv[currentArgIndex],"-ec")==0) 
	    {
	      ecSelected=true;
	      std::cout << "Generating extent of contamination impact file" << std::endl;
	    } 
	  else if(strcmp(argv[currentArgIndex],"-pk")==0) 
	    {
	      pkSelected=true;
	      if(currentArgIndex==(argc-1))
		{
		  std::cerr << "***TAI input file not supplied - required for computation of population fatalities objective" << std::endl;
		  exit(1);
		}
	      taiInputFilename=argv[++currentArgIndex];
	      std::cout << "Generating population killed impact file" << std::endl;
	    } 
	  else if(strcmp(argv[currentArgIndex],"-pe")==0) 
	    {
	      peSelected=true;
	      if(currentArgIndex==(argc-1))
		{
		  std::cerr << "***TAI input file not supplied - required for computation of population exposed objective" << std::endl;
		  exit(1);
		}
	      taiInputFilename=argv[++currentArgIndex];
	      std::cout << "Generating population exposed impact file" << std::endl;
	    } 
	  else if(strcmp(argv[currentArgIndex],"-tsoPattern")==0) 
	    {
	      if(currentArgIndex==(argc-1))
		{
		  std::cerr << "***TSO file pattern not supplied" << std::endl;
		  exit(1);
		}
	      tsoPattern=argv[++currentArgIndex];
	    } 
	  else if(strcmp(argv[currentArgIndex],"-detectionDelay")==0) 
	    {
	      detectionDelay=atoi(argv[++currentArgIndex]);
	      if(detectionDelay<0)
		{
		  std::cerr << "***The detection delay must be non-negative" << std::endl;
		  exit(1);
		}
	      std::cout << "Detection delay (in minutes)=" << detectionDelay << std::endl;
	    } 
	  else if(strcmp(argv[currentArgIndex],"-minQuality")==0) 
	    {
	      minQuality=atof(argv[++currentArgIndex]);
	      if(minQuality<0.0)
		{
		  std::cerr << "***The minimum water quality must be non-negative" << std::endl;
		  exit(1);
		}
	      std::cout << "Water quality threshold=" << minQuality << std::endl;
	    } 
#if 0
	  else if(strcmp(argv[currentArgIndex],"-sensorFile")==0) 
	    {
	      if(currentArgIndex==(argc-1))
		{
		  std::cerr << "***Sensor input file not supplied" << std::endl;
		  exit(1);
		}
	      sensorInputFilename=argv[++currentArgIndex];
	      std::cout << "Sensor input file=" << sensorInputFilename << std::endl;
	    } 
#endif
	  else if(strcmp(argv[currentArgIndex],"-tsoPattern")==0) 
	    {
	      tsoPattern=argv[currentArgIndex];
	      std::cout << "TSO filename pattern=" << tsoPattern << std::endl;
	    } 
	  else if(strcmp(argv[currentArgIndex],"-epanetin")==0)
	    {
	      if(currentArgIndex==(argc-1))
		{
		  std::cerr << "***EPANET input file not supplied" << std::endl;
		  exit(1);
		}
	      epanetInputFilename=argv[++currentArgIndex];
	    }
	  else 
	    {
	      std::cerr << "***Unknown argument=" << argv[currentArgIndex] << std::endl;
	      exit(1);
	    }

	  currentArgIndex++;
	}

      ////////////////////////////////////////////////////////

      //////////////////////////////////////////////////////////////
      // read in the sensor locations, if any have been specified //
      // NOTE: the indicies in the input file are 1-based, and    //
      //       are converted to 0-based indicies for internal use //
      // NOTE: the program assumes the indices in the input file  //
      //       are identical to those found in the tso2Impact     //
      //       nodemap output file.                               //
      //////////////////////////////////////////////////////////////

      if(sensorInputFilename!="")
	{
	  std::ifstream sensorInputFile(sensorInputFilename.c_str());
	  if(!sensorInputFile)
	    {
	      std::cerr << "***Failed to open sensor input file=" << sensorInputFilename << std::endl;
	      exit(1);
	    }
      
	  for(;;)
	    {
	      int thisSensorIndex;
	      sensorInputFile >> thisSensorIndex;
	      if(!sensorInputFile)
		{
		  break;
		}
	      sensorLocations.push_back(thisSensorIndex-1);
	    }

	  std::cout << "Number of sensor locations=" << sensorLocations.size() << std::endl;
	  sensorInputFile.close();
	}

      //////////////////////////////////////////////////////////////
}

void readTsoInfo(int& numNodes,
	PNodeInfo&nodes, PLinkInfo&links,
	PNetInfo&net, PTSO&tso, PSource&sources,
	std::string&outputFilePrefix,
	std::string&tsoFileOrDirectoryName,
	std::string&tsoPattern,
	std::string&nodeMapFileName,
	std::string&scenarioMapFileName,
	std::ofstream&nodeMapFile,
	std::ofstream&scenarioMapFile,
        std::vector<std::string>&nodeIndexToIDMap,
        std::map<std::string,int>&nodeIDToIndexMap)
{
      nodeMapFileName = outputFilePrefix+"."+NODE_MAP_FILE_SUFFIX;
      scenarioMapFileName = outputFilePrefix+"."+SCENARIO_MAP_FILE_SUFFIX;
      nodeMapFile.open(nodeMapFileName.c_str()); 
      scenarioMapFile.open(scenarioMapFileName.c_str()); 
      nodeMapFileName = outputFilePrefix+"."+NODE_MAP_FILE_SUFFIX;
      std::cout << std::endl << "Loading TSO File..." << std::endl;
      if(tsoPattern=="")
	{
	  tso=TSO_Open((char*)tsoFileOrDirectoryName.c_str(),0);
	}
      else 
	{
	  tso=TSO_Open((char*)tsoFileOrDirectoryName.c_str(),(char*)tsoPattern.c_str());
	}
      std::cout << "Opened tso file" << std::endl;

      TSO_ReadPrologue(tso,&net,&nodes,&links);
      numNodes = net->nnodes;
      nodeIndexToIDMap= std::vector<std::string>(numNodes);
  
      std::cout << "Current file=" << tso->curFile << std::endl;
      std::cout << "Storage method=" << tso->storageMethod << std::endl;
      std::cout << "File version=" << tso->fileVersion << std::endl;

      std::cout << std::endl;
      std::cout << "Number of nodes=" << net->nnodes << std::endl;
      std::cout << "Number of links=" << net->nlinks << std::endl;
      std::cout << "Number of tanks=" << net->ntanks << std::endl;
      std::cout << "Number of junctions=" << net->njunctions << std::endl;
      std::cout << "Number of steps=" << net->nsteps << std::endl;
      std::cout << "Number of species=" << net->nspecies << std::endl;
      for(int i=0;i<net->nspecies;i++)
	{
	  std::cout << "Species=" << net->species[i] << std::endl;
	}
      std::cout << "Step size (hours)=" << net->stepsize << std::endl; // units appear to be in hours!!!
      std::cout << "Floatmax=" << net->fltmax << std::endl;
      std::cout << std::endl;

      #ifdef OUTPUT_TSO_DETAIL

      std::cout << std::endl;
      std::cout << "Node hydraulic information" << std::endl << std::endl;
      for(int i=0;i<net->nnodes;i++)
	{
	  std::cout << "Node (index=" << i+1 << ",ID=" << nodes[i].id << ") ";
	  std::cout << "Demands= ";
	  for(int j=0;j<net->nsteps;j++)
	    {
	      std::cout << nodes[i].q[j] << " ";
	    }
	  std::cout << std::endl;
	}
      std::cout << std::endl;

      #endif

      // NOTE: internal to tso2Impact.cc, the node indicies are 0-based, in
      //       correspondence with the TEVA node/link arrays. More annoyingly,
      //       the indicies maintained in the TEVA data structures are 1-based,
      //       requiring corrections when accessing the data structures.
      //       ALL external writes perform a 1-based translation.

      // a simple file to assist in translation between (1-based)
      // auxilliary node indicies and the real node names.


      for(int i=0;i<net->nnodes;i++)
	{
	  nodeMapFile << i+1 << " " << nodes[i].id << std::endl;

	  nodeIndexToIDMap[i]=nodes[i].id;
	  nodeIDToIndexMap[nodes[i].id]=i;
	}

      nodeMapFile.close();
  
      #ifdef OUTPUT_TSO_DETAIL

      std::cout << std::endl;
      std::cout << "Link hydraulic information" << std::endl << std::endl;
      for(int i=0;i<net->nlinks;i++)
	{
	  std::cout << "Link (Index=" << links[i].from << ",ID=" << nodes[(links[i].from)-1].id << " => Index=" << links[i].to << ",ID=" << nodes[(links[i].to)-1].id << ")" << std::endl;
	  std::cout << "Velocities= ";
	  for(int j=0;j<net->nsteps;j++)
	    {
	      std::cout << links[i].velocity[j] << " ";
	    }
	  std::cout << std::endl;
	  std::cout << "Flows= ";
	  for(int j=0;j<net->nsteps;j++)
	    {
	      std::cout << links[i].flow[j] << " ";
	    }
	  std::cout << std::endl;
	}
      std::cout << std::endl;

      #endif
}

void initStandaloneTso2Impact(
	int& numNodes, clock_t&start, clock_t& stop, 
	PNodeInfo&nodes, PLinkInfo&links,
	PNetInfo&net, PTSO&tso, PSource&sources,
	std::string&outputFilePrefix,
	std::string&tsoFileOrDirectoryName,
	int&detectionDelay,
	double&minQuality,
	bool&mcSelected,
	bool&vcSelected,
	bool&nfdSelected,
	bool&tdSelected,
	bool&ecSelected,
	std::string&epanetInputFilename,
	bool&pkSelected,
	bool&peSelected,
	std::string&taiInputFilename,
	PMem& assessMem,
	std::string&tsoPattern,
	std::string&sensorInputFilename,
	std::list<int>&sensorLocations,
	std::string&nodeMapFileName,
	std::string&scenarioMapFileName,
	std::ofstream&nodeMapFile,
	std::ofstream&scenarioMapFile,
	std::vector<ObjectiveBase*>&theObjectives,
        std::vector<std::string>&nodeIndexToIDMap,
        std::map<std::string,int>&nodeIDToIndexMap)
{
	readTsoInfo(numNodes,
		nodes, links,
		net, tso, sources,
		outputFilePrefix,
		tsoFileOrDirectoryName,
		tsoPattern,
		nodeMapFileName,
		scenarioMapFileName,
		nodeMapFile,
		scenarioMapFile,
        	nodeIndexToIDMap,
        	nodeIDToIndexMap);
	initTso2ImpactAfterTsoRead(
		numNodes, start, stop, 
		nodes, links,
		net, tso, sources,
		outputFilePrefix,
		tsoFileOrDirectoryName,
		detectionDelay,
		minQuality,
		mcSelected,
		vcSelected,
		nfdSelected,
		tdSelected,
		ecSelected,
		epanetInputFilename,
		pkSelected,
		peSelected,
		taiInputFilename,
		assessMem,
		tsoPattern,
		sensorInputFilename,
		sensorLocations,
		nodeMapFileName,
		scenarioMapFileName,
		nodeMapFile,
		scenarioMapFile,
		theObjectives,
		nodeIndexToIDMap,
		nodeIDToIndexMap);
}


void finalizeTheObjectives(std::vector<ObjectiveBase*>&theObjectives)
{
      for(size_t i=0;i<theObjectives.size();i++)
	{
	  theObjectives[i]->finalize();
	  delete theObjectives[i];
	}

      theObjectives.clear();
}
