package org.coinor.opents.net;
import java.rmi.*;

public class ClusterClientApplet extends java.applet.Applet 
{

    public void init() 
    {
        initComponents();
        postForteInitComponents();
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        label1 = new java.awt.Label();
        
        setLayout(new java.awt.BorderLayout());
        
        label1.setText("label1");
        add(label1, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

    
    
    
    private void postForteInitComponents()
    {
        try
        {
            AppletPOC poc = (AppletPOC) Naming.lookup("//" + getCodeBase().getHost() + "/AppletPOC");
            poc.registerClientTabuSearchFactoryRemote( new ClientTabuSearchFactoryImpl() );
        }   // end try
        catch( NotBoundException e ){
            e.printStackTrace();
        }   // end catch
        catch( RemoteException e ){
            e.printStackTrace();
        }   // end catch
        catch( java.net.MalformedURLException e ){
            e.printStackTrace();
        }   // end catch
        System.out.println( "Successfully registered self with AppletPOC" );
    }   // end
    
    
    
}
