#!/bin/sh
##
## Dummy script that calls testdriver to manage configuration, builds
## and testing
##

./packages/acro-pico/packages/exact/src/testing/testdriver --I=packages/acro-pico/packages/exact/src/testing --S=config $*

