/*  _________________________________________________________________________
 *
 *  PICO: A C++ library of scalable branch-and-bound and related methods.
 *  Copyright (c) 2001, Sandia National Laboratories.
 *  This software is distributed under the GNU Lesser General Public License.
 *  For more information, see the README file in the top PICO directory.
 *  _________________________________________________________________________
 */
//
// setupMappedMILP.cpp
//
// Creates a MILP application that includes symbols from the variable and 
// constraint names!
//

#include <acro_config.h>
#include <utilib/_math.h>
#include <utilib/seconds.h>
#include <utilib/ParameterList.h>
#include <utilib/memdebug.h>
#include <pebbl/fundamentals.h>
#include <pico/milp.h>

using namespace utilib;
using namespace pico;
using namespace std;


int main(int argc, char** argv)
{
utilib::exception_mngr::set_mode(utilib::exception_mngr::Abort);
CommonIO::begin();
try {

signal(SIGFPE,pebbl_abort_handler);

int debug=0;
bool preprocessLP=false;

utilib::ParameterSet params;
params.create_parameter("debug",debug,"<int>","0",
	"TODO",utilib::ParameterLowerBound<int>(0));
params.create_parameter("preprocessLP",preprocessLP,
	"<bool>","false","TODO");

ParameterList plist;
plist.register_parameters(params);
plist.register_parameters<MILPProblem>();
plist.process_parameters(argc,argv,1);
params.set_parameters(plist,false);
if (params.get_parameter<bool>("help")) {
plist.write_registered_parameters(cout);
return -1;
}

BasicArray<int> listOfInts;
CharString mapfile, rowlabels, collabels;

//
// PICO's parameter processing... (need this here????)
//
//parameter::readAll(argc, argv, 0, 10);
//
// My parameter processing...
//
if (argc == 1) {
   ucout << "setupMappedMILP [-labels <rowfile> <colfile>] [-mapfile <mapfile>] <lp-file> <ofile-name>\n";
   ucout.flush();
   CommonIO::end();
   return ERR;
   }
int argctr=1;
if (strcmp(argv[argctr],"-labels") == 0) {
   argctr++;
   rowlabels = argv[argctr++];
   collabels = argv[argctr++];
   }
if (strcmp(argv[argctr],"-mapfile") == 0) {
   mapfile = argv[argctr+1];
   argctr += 2;
   }
MILPProblem problem;
problem.lp.init(pico::PicoLPSolver::defaultLP);
problem.lp()->loadProblem(argv[argctr++], listOfInts);
//
// Here, we reset the name of the LP to make it consistent with the
// name of the MPS file.  This is necessary, since this label is what is
// used to find other files generated by gen_milp_app
//
CharString lpname = argv[argctr];
char* str = strrchr(lpname.data(), (int)'.');
if (str != NULL)
   lpname.resize(str - lpname.data());
problem.lp()->setName(lpname.data());

CharString fname = argv[argctr++];

//
// Write out debugging information
//
if (debug) {
   problem.lp()->write(ucout,verbose_format);
   ucout << Flush;
   }
/*
if (listOfInts.size() == 0) {
   ucout << "No integer variables... no apparent need to generate a mapped LP." << endl;
   CommonIO::end();
   return 0;
   }
*/

problem.initialize(listOfInts, debug);
if (rowlabels != "")
   problem.set_labels(rowlabels,collabels);
if (params.get_parameter<bool>("preprocessLP"))
   problem.preprocess();
problem.generate_mapped_milp(fname,mapfile);

}
catch (const char* str) {
  cerr << "ERROR: setupMappedMILP caught error: " << str << endl;
  }
catch (std::exception& err) {
  cerr << "ERROR: setupMappedMILP caught exception: " << err.what() << endl;
  }

CommonIO::end();
return 0;
}
