/*
 * Copyright � 2008 UChicago Argonne, LLC
 * NOTICE: This computer software, TEVA-SPOT, was prepared for UChicago Argonne, LLC
 * as the operator of Argonne National Laboratory under Contract No. DE-AC02-06CH11357
 * with the Department of Energy (DOE). All rights in the computer software are reserved
 * by DOE on behalf of the United States Government and the Contractor as provided in
 * the Contract.
 * NEITHER THE GOVERNMENT NOR THE CONTRACTOR MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR
 * ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.
 *
 * This software is distributed under the BSD License.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class anl_teva_db_TSOReader */

#ifndef _Included_anl_teva_db_TSOReader
#define _Included_anl_teva_db_TSOReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     anl_msv_dpf_erd_db_TSOReader
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;CC)I
 */
JNIEXPORT jlong JNICALL Java_anl_msv_dpf_erd_db_TSOReader_open
  (JNIEnv *, jobject, jstring, jstring, jchar, jchar);

/*
 * Class:     anl_msv_dpf_erd_db_TSOReader
 * Method:    positionAfterPrologue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_anl_msv_dpf_erd_db_TSOReader_positionAfterPrologue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     anl_msv_dpf_erd_db_TSOReader
 * Method:    readPrologue
 * Signature: (I[Ljava/lang/Object;[I)V
 */
JNIEXPORT void JNICALL Java_anl_msv_dpf_erd_db_TSOReader_readPrologue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     anl_msv_dpf_erd_db_TSOReader
 * Method:    closeAndFreeMemory
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_anl_msv_dpf_erd_db_TSOReader_closeAndFreeMemory
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     anl_msv_dpf_erd_db_TSOReader
 * Method:    readSimulationResults
 * Signature: (IIII[[F)Z
 */
JNIEXPORT jboolean JNICALL Java_anl_msv_dpf_erd_db_TSOReader_readSimulationResults
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobjectArray, jobjectArray);

/*
 * Class:     anl_msv_dpf_erd_db_TSOReader
 * Method:    getSimulationResults
 * Signature: (IIII[[F)V
 */
JNIEXPORT jboolean JNICALL Java_anl_msv_dpf_erd_db_TSOReader_getSimulationResults
  (JNIEnv *, jobject, jint, jlong, jlong, jlong, jlong, jobjectArray, jobjectArray);

/*
 * Class:     anl_msv_dpf_erd_db_TSOReader
 * Method:    getRawSimulationResults
 * Signature: (IIII[[F)V
 */
JNIEXPORT jboolean JNICALL Java_anl_msv_dpf_erd_db_TSOReader_getRawSimulationResults
  (JNIEnv *, jobject, jint, jlong, jlong, jlong, jlong, jobjectArray, jbyteArray);

/*
 * Class:     anl_msv_dpf_erd_db_TSOReader
 * Method:    getIndex
 * Signature: (IIII)[Lanl/teva/dp/db/DataIndex
 */
JNIEXPORT jobject JNICALL Java_anl_msv_dpf_erd_db_TSOReader_getIndex
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
