#
# Perform functionality test for tso2Impact
#
import os
import sys

######################################################
# Path variables were set by test/runtests.py
#
sys.path.insert(0, ".."+os.sep+"..")
import path
pydirs=path.PYTHON_DIRECTORIES
datadir=path.DATA_DIR+os.sep
spotbin=path.SPOT_BIN+os.sep

dirs = pydirs.split(";")
for dir in dirs:
  sys.path.insert(0, dir)

currdir = os.path.dirname(os.path.abspath(__file__)) + os.sep
#
#
######################################################

datadir = datadir+os.sep+"Net3"+os.sep

import unittest
import pyutilib_th
import pyutilib
from nose.tools import nottest

#
# Check to see if tso2Impact is compiled with health impact options
#
pyutilib.run_command(spotbin+"tso2Impact --help",currdir+"tmp.out")
using_health_impacts = False
INPUT = open(currdir+"tmp.out")
for line in INPUT:
    if "--pe" in line:
        using_health_impacts=True
os.remove(currdir+"tmp.out")

#
# Create unittest testing class
#
# Methods test_* are executed (in an arbitrary order)
# The setUp() method is run before every test.
# The tearDown() method is run after every test.
#
# TODO: I think we can be more clever, and create the test1(), test2(), ... methods
# automatically.
#
class Test_tso2Impact(pyutilib_th.TestCase):

    def create_command(self, network, impacts, frequency, name=None, tai_file=""):
        """ Create the command line """
        if name is None:
           name = network+"_"+frequency
        return spotbin+"tso2Impact "+" --" + impacts + " --epanetin "+datadir+network+".inp"+" "+name+" "+datadir+network+"_"+frequency+".tso " + tai_file

    @nottest
    def execute_test(self, network, frequency, impact, name):
        """ Execute a test given different information """
        basename=network+"_"+frequency
        if impact in ["pd","pk","pe","dpd","dpk","dpe"]:
            tai_file = datadir+"bio.tai"
            testname=basename+"_bio"
        else:
            tai_file = ""
            testname=network+"_"+frequency
        print "Running",self.create_command(network,impact,frequency,testname,tai_file)
        pyutilib.run_command(self.create_command(network,impact,frequency,tai_file=tai_file, name=testname), currdir+name+".out",cwd=currdir)
        #
        # Compare various files generated by tso2Impact against reference versions
        #
        file=testname+"_"+impact+".impact"
        self.failUnlessFileEqualsBaseline(currdir+file,datadir+file)
        file=testname+"_"+impact+".impact.id"
        self.failUnlessFileEqualsBaseline(currdir+file,datadir+file)
        file=basename+".nodemap"
        self.failUnlessFileEqualsBaseline(currdir+file,datadir+file)
        file=basename+".scenariomap"
        self.failUnlessFileEqualsBaseline(currdir+file,datadir+file)
        os.remove(currdir+name+".out")

    def test_ec(self):
        """ tso2Impact tested on Net3_quarterly ec """
        self.execute_test("Net3","quarterly","ec","test_ec")

    def test_vc(self):
        """ tso2Impact tested on Net3_quarterly vc """
        self.execute_test("Net3","quarterly","vc","test_vc")

    def test_td(self):
        """ tso2Impact tested on Net3_quarterly td """
        self.execute_test("Net3","quarterly","td","test_td")

    def test_mc(self):
        """ tso2Impact tested on Net3_quarterly mc """
        self.execute_test("Net3","quarterly","mc","test_mc")

    def test_dec(self):
        """ tso2Impact tested on Net3_quarterly dec """
        self.execute_test("Net3","quarterly","dec","test_dec")

    def test_dvc(self):
        """ tso2Impact tested on Net3_quarterly dvc """
        self.execute_test("Net3","quarterly","dvc","test_dvc")

    def test_dtd(self):
        """ tso2Impact tested on Net3_quarterly dtd """
        self.execute_test("Net3","quarterly","dtd","test_dtd")

    def test_dmc(self):
        """ tso2Impact tested on Net3_quarterly dmc """
        self.execute_test("Net3","quarterly","dmc","test_dmc")

    def test_nfd(self):
        """ tso2Impact tested on Net3_quarterly nfd """
        self.execute_test("Net3","quarterly","nfd","test_nfd")

    def Xtest_pe(self):
        """ tso2Impact tested on Net3_quarterly pe """
        if not using_health_impacts:
            return
        self.execute_test("Net3","quarterly","pe","test_pe")

    def Xtest_pk(self):
        """ tso2Impact tested on Net3_quarterly pk """
        if not using_health_impacts:
            return
        self.execute_test("Net3","quarterly","pk","test_pk")

    def Xtest_pd(self):
        """ tso2Impact tested on Net3_quarterly pd """
        if not using_health_impacts:
            return
        self.execute_test("Net3","quarterly","pd","test_pd")

    def Xtest_dpe(self):
        """ tso2Impact tested on Net3_quarterly dpe """
        if not using_health_impacts:
            return
        self.execute_test("Net3","quarterly","dpe","test_dpe")

    def Xtest_dpk(self):
        """ tso2Impact tested on Net3_quarterly dpk """
        if not using_health_impacts:
            return
        self.execute_test("Net3","quarterly","dpk","test_dpk")

    def Xtest_dpd(self):
        """ tso2Impact tested on Net3_quarterly dpd """
        if not using_health_impacts:
            return
        self.execute_test("Net3","quarterly","dpd","test_dpd")

    def Xtest_largeQuality1(self):
        """ Verify that a very large quality creates an impact with only dummy detections for mc """
        network="Net3"
        frequency="quarterly"
        testname=network+"_"+frequency
        impact="mc"
        cmd = self.create_command(network,impact,frequency,testname)
        items = cmd.split(" ")
        cmd = items[0] + " --detectionLimit 1000000.0 " + " ".join(items[1:])
        print "Running",cmd
        pyutilib.run_command(cmd, "largeQuality_mc.out", cwd=currdir)
        file=testname+"_"+impact+".impact"
        self.failUnlessFileEqualsBaseline(currdir+file,currdir+"largeQuality_mc.impact")
        os.remove(currdir+"largeQuality_mc.out")
        
    def Xtest_largeQuality2(self):
        """ Verify that a very large quality does not impact the value of dummy detections for 'ec' """
        network="Net3"
        frequency="quarterly"
        testname=network+"_"+frequency
        impact="ec"
        cmd = self.create_command(network,impact,frequency,testname)
        items = cmd.split(" ")
        cmd = items[0] + " --detectionLimit 1000000.0 " + " ".join(items[1:])
        print "Running",cmd
        pyutilib.run_command(cmd, "largeQuality_ec.out", cwd=currdir)
        file=testname+"_"+impact+".impact"
        self.failUnlessFileEqualsBaseline(currdir+file,currdir+"largeQuality_ec.impact")
        os.remove(currdir+"largeQuality_ec.out")
        
    def Xtest_multi_quality(self):
        """ Verify that tso2Impact can work with multiple quality values """
        cmd = spotbin+"tso2Impact "+" --detectionLimit 100000.0 --detectionLimit 100000.0 --mc --epanetin "+etcdir+"Net3.inp multi_quality "+etcdir+"Net3/Net3_hourly.tso "+etcdir+"Net3/Net3_quarterly.tso"
        print "Running "+cmd
        pyutilib.run_command(cmd, "multi_quality.out", cwd=currdir)
        self.failUnlessFileEqualsBaseline(currdir+"multi_quality_mc.impact",currdir+"multi_quality.impact")
        os.remove(currdir+"multi_quality.out")
        os.remove(currdir+"multi_quality_mc.impact.id")
        os.remove(currdir+"multi_quality.nodemap")
        os.remove(currdir+"multi_quality.scenariomap")

    def Xtest_responseTime1(self):
        """ Verify that a nonzero responseTime increases impacts, except for the dummy """
        #
        # This was confirmed by visual inspection.  A more precise test would
        # compare the impact files with/without a response time.
        #
        cmd = spotbin+"tso2Impact "+" --responseTime 100.0 --mc --epanetin "+etcdir+"Net3.inp responseTime1 "+etcdir+"Net3/Net3_quarterly.tso"
        print "Running "+cmd
        pyutilib.run_command(cmd, "responseTime1.out", cwd=currdir)
        self.failUnlessFileEqualsBaseline(currdir+"responseTime1_mc.impact",currdir+"responseTime1.impact")
        os.remove(currdir+"responseTime1.out")
        os.remove(currdir+"responseTime1_mc.impact.id")
        os.remove(currdir+"responseTime1.nodemap")
        os.remove(currdir+"responseTime1.scenariomap")

#
# Run the tests
#
# To run a single test, you can execute:
#
#    python test_tso2Impact.py Test_tso2Impact.test_test1
#
# TODO: simplify this...
#
def main():
    suite = unittest.TestLoader().loadTestsFromTestCase(Test_tso2Impact)
    unittest.TextTestRunner(verbosity=2).run(suite)

if __name__ == "__main__":
    unittest.main()

