/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class anl_msv_dpf_erd_db_ERDReader */

#ifndef _Included_anl_msv_dpf_erd_db_ERDReader
#define _Included_anl_msv_dpf_erd_db_ERDReader
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     anl_msv_dpf_erd_db_ERDReader
 * Method:    open
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_anl_msv_dpf_erd_db_ERDReader_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     anl_msv_dpf_erd_db_ERDReader
 * Method:    getIndex
 * Signature: (JJ)[Lanl/msv/dpf/erd/db/ERDDataIndex;
 */
JNIEXPORT jobjectArray JNICALL Java_anl_msv_dpf_erd_db_ERDReader_getIndex
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     anl_msv_dpf_erd_db_ERDReader
 * Method:    closeAndFreeMemory
 * Signature: (JJJJJ)V
 */
JNIEXPORT void JNICALL Java_anl_msv_dpf_erd_db_ERDReader_closeAndFreeMemory
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     anl_msv_dpf_erd_db_ERDReader
 * Method:    getSimulationResults
 * Signature: (IJJJJ[Lanl/msv/dpf/erd/db/NodeInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_anl_msv_dpf_erd_db_ERDReader_getSimulationResults
  (JNIEnv *, jobject, jint, jlong, jlong, jlong, jlong, jobjectArray, jobjectArray);

/*
 * Class:     anl_msv_dpf_erd_db_ERDReader
 * Method:    getRawSimulationResults
 * Signature: (IJJJJ[Lanl/msv/dpf/erd/db/NodeInfo;[B)V
 */
JNIEXPORT jboolean JNICALL Java_anl_msv_dpf_erd_db_ERDReader_getRawSimulationResults
  (JNIEnv *, jobject, jint, jlong, jlong, jlong, jlong, jobjectArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
