/*  _________________________________________________________________________
 *
 *  PICO: A C++ library of scalable branch-and-bound and related methods.
 *  Copyright (c) 2001, Sandia National Laboratories.
 *  This software is distributed under the GNU Lesser General Public License.
 *  For more information, see the README file in the top PICO directory.
 *  _________________________________________________________________________
 */
//
// serialMilpParams.cpp
//

// Defines parameters, etc, used for general mixed-integer linear programming
//

#include <acro_config.h>
#include <utilib/ValidateParameter.h>
#include <pico/serialMilpParams.h>

using namespace std;
namespace pico{

serialMilpParams::serialMilpParams()
{
useSets=true;
create_parameter("useSets",useSets,"<bool>","true",
		"Automatically detect and use special ordered sets of the form\n\t(sum binary vars) = 1.  Assume order in matrix.");

giveSetsPriority=true;
create_parameter("giveSetsPriority",giveSetsPriority,"<bool>","true",
		"If true and special ordered sets are on, always branch on one\n\tof them if possible");

rootLP=false;
create_parameter("rootLP",rootLP, "<bool>","false","TODO");

preprocessOnly=false;
create_parameter("preprocessOnly",preprocessOnly,
                "<bool>","false","TODO");

onlyRootLP=false;
create_parameter("onlyRootLP",onlyRootLP, "<bool>","false",
                "TODO");

saveRootBoundingInfo=false;
create_parameter("saveRootBoundingInfo",saveRootBoundingInfo,
	"<bool>","false",
                "Output root bounding information (e.g. values of integer\n\t"
                "variables) to the file root-bounding-info.bin.");

allowPseudoEnumeration=true;
create_parameter("allowPseudoEnumeration",allowPseudoEnumeration,
	"<bool>","true",
        "If true, then allow the enumeration of near optimal solutions\n\t"
	"without checking whether integral solutions generated by LPs\n\t"
	"have alternative solutions.");
}

}
