#
# Perform functionality test for aggregateImpacts
#
import os
import sys
from os.path import abspath, dirname
sys.path.insert(0, dirname(dirname(abspath(__file__)))+os.sep+".."+os.sep+"..")
currdir = dirname(abspath(__file__))+os.sep

import unittest
import pyutilib
import pyutilib_th
from tevaspot import pyunit
from nose.tools import nottest
import shutil

netdir = pyunit.datadir + "Net3" + os.sep
modeldir=pyunit.moddir

#
# Create unittest testing class
#
# Methods test_* are executed (in an arbitrary order)
# The setUp() method is run before every test.
# The tearDown() method is run after every test.
#
class Test(pyutilib_th.TestCase):

    def create_command(self, infile, nlines):
        """ Create the command line """
        return "aggregateImpacts --read-limit "+ str(nlines) + " " + infile

    @nottest
    def execute_test(self, name, nlines):
        """ Execute a test given different information """

        cmd = self.create_command(currdir+name+".config", nlines)
        print "Running",cmd
        pyutilib.run_command(cmd, currdir+name+".out", cwd=currdir)
        #
        # Compare various files generated by scenarioAggr against reference versions
        #
        self.failUnlessFileEqualsBaseline(currdir+name+"_agg.impact",currdir+name+"_agg.txt")
        #os.remove(currdir+name+".impacts")
        #os.remove(currdir+name+".out")

    # Tests with distinguished detection 

    def test1a_0(self):
        """ aggregateImpacts tested on test1a.impact - no limit"""
        self.execute_test("test1a", 0)

    def test2a_0(self):
        """ aggregateImpacts tested on test2a.impact - no limit"""
        self.execute_test("test2a", 0)

    def test3a_0(self):
        """ aggregateImpacts tested on test3a.impact - no limit"""
        self.execute_test("test3a", 0)

    def test4a_0(self):
        """ aggregateImpacts tested on test4a.impact - no limit"""
        self.execute_test("test4a", 0)

    # Tests with fixed locations

    def test2c_0(self):
        """ aggregateImpacts tested on test2c.impact - no limit"""
        self.execute_test("test2c", 0)

    def test3c_0(self):
        """ aggregateImpacts tested on test3c.impact - no limit"""
        self.execute_test("test3c", 0)

    def test4c_0(self):
        """ aggregateImpacts tested on test4c.impact - no limit"""
        self.execute_test("test4c", 0)

if __name__ == "__main__":
    unittest.main()

