/* TEVA header */

#include "teva.h"
#include "version.h"
#include <utilib/OptionParser.h>

extern "C" {
void run_tevasim(int tsofileversion, const char* tsgfname, const char* tsifname, const char* tsofname, const char* epanetinpfname, const char* epanetoutfname);
};

int main(int argc, char **argv)
/*
**--------------------------------------------------------------
** Module:  TEVA
** Usage:   tevasim [-s StorageMethod] [-tsg tsg-file] [-tsi tsi-file] [-tso tso-file] <epanet-input-file> <epanet-output-file>
** Input:   EPANET input file, threat simulation generator or input file
** Output:  program status, epanet output, simulation output database
** Purpose: generate tso format database of water quality data for specified
**          threat simulations
**---------------------------------------------------------------
*/
{
int tsofileversion=TSOFILEVERSION;
std::string tsgfname;
std::string tsifname;
std::string tsofname;
std::string epanetinpfname;
std::string epanetoutfname;

utilib::OptionParser options;
std::string version = create_version("tevasim",__DATE__,__TIME__);

options.version(version);
options.add_usage("tevasim [options] <epanet-input-file> <epanet-output-file>");
options.description="A utility for running an ensemble of water quality simulations, whose results are stored in a TSO file.";
options.add('v',"tso-version",tsofileversion,"The version of the TSO format that is generated");
options.add("tsg",tsgfname,"The TSG file used to specify the injection incidents.");
options.add("tsi",tsifname,"The TSI file used to specify the injection incidents.");
options.add("tso",tsofname,"The TSO output file.");

options.add_argument("epanet-input-file","EPANET network file.");
options.add_argument("epanet-output-file","Output file generated by EPANET.");

options.epilog="The tevasim command is used to simulate contamination incidents. This command uses EPANET to perform an ensemble of contaminant transport simulations, defined by a TSG File. The following files are generated during the execution of tevasim:\n\
  - a binary TSO file that contains the contamination transport data,\n\
  - a binary SDX file that provides an index into the TSO File, and\n\
  - an output file that provides a textual summary of the EPANET simulations.\n\
\n\
Note that options like 'tso' can be specified with the syntax '--tso file.tso' or '--tso=file.tso'.";

utilib::OptionParser::args_t args = options.parse_args(argc,argv);

if(tsofileversion<1 || tsofileversion>TSOFILEVERSION) TEVASimError(1,"Invalid TSO File Version Flag\n");

//
// Check for errors in the command-line arguments
//
   if (options.help_option())
   {
      options.write(std::cout);
      return 1;
   }
   if (options.version_option())
   {
      options.print_version(std::cout);
      return 1;
   }

if (args.size() != 3)
{
   options.write(std::cerr);
   exit(9);
}
utilib::OptionParser::args_t::iterator curr = args.begin();
curr++;
epanetinpfname=*curr;
curr++;
epanetoutfname=*curr;

const char *tsg=NULL, *tsi=NULL, *tso=NULL;
if (tsifname != "")
   tsi=tsifname.c_str();
if (tsgfname != "")
   tsg=tsgfname.c_str();
if (tsofname != "")
   tso=tsofname.c_str();

run_tevasim(tsofileversion, tsg, tsi, tso, epanetinpfname.c_str(), epanetoutfname.c_str());

return 0;
}
