#! /usr/bin/env python
#
# Script to bootstrap the Acro configuration fragments, and then apply
# configuration, build and analysis operations.
#

import os
import sys
sys.path.insert(0, os.getcwd()+'/admin')
import setup

setup.run()

