/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class anl_teva_analysis_module_ExternalAnalysisAggregationServerImpl */

#ifndef _Included_anl_teva_analysis_module_ExternalAnalysisAggregationServerImpl
#define _Included_anl_teva_analysis_module_ExternalAnalysisAggregationServerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     anl_teva_analysis_module_ExternalAnalysisAggregationServerImpl
 * Method:    getResults
 * Signature: (Lanl/teva/analysis/module/NamedDataServer;Lanl/teva/analysis/module/AnalysisResults;)V
 */
JNIEXPORT void JNICALL Java_anl_teva_analysis_module_ExternalAnalysisAggregationServerImpl_getResults
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     anl_teva_analysis_module_ExternalAnalysisAggregationServerImpl
 * Method:    init
 * Signature: (Lanl/teva/analysis/module/NamedDataServer;)V
 */
JNIEXPORT void JNICALL Java_anl_teva_analysis_module_ExternalAnalysisAggregationServerImpl_init
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     anl_teva_analysis_module_ExternalAnalysisAggregationServerImpl
 * Method:    shutdown
 * Signature: (Lanl/teva/analysis/module/NamedDataServer;)V
 */
JNIEXPORT void JNICALL Java_anl_teva_analysis_module_ExternalAnalysisAggregationServerImpl_shutdown
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     anl_teva_analysis_module_ExternalAnalysisAggregationServerImpl
 * Method:    newResults
 * Signature: (Lanl/teva/analysis/module/NamedDataServer;Lanl/teva/analysis/module/NamedData;)V
 */
JNIEXPORT void JNICALL Java_anl_teva_analysis_module_ExternalAnalysisAggregationServerImpl_newResults
  (JNIEnv *, jobject, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
