/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class anl_teva_analysis_module_ExternalIntermediateAnalysisServerImpl */

#ifndef _Included_anl_teva_analysis_module_ExternalIntermediateAnalysisServerImpl
#define _Included_anl_teva_analysis_module_ExternalIntermediateAnalysisServerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     anl_teva_analysis_module_ExternalIntermediateAnalysisServerImpl
 * Method:    init
 * Signature: (Lanl/teva/analysis/module/NamedDataServer;)V
 */
JNIEXPORT jboolean JNICALL Java_anl_teva_analysis_module_ExternalIntermediateAnalysisServerImpl_init
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     anl_teva_analysis_module_ExternalIntermediateAnalysisServerImpl
 * Method:    shutdown
 * Signature: (Lanl/teva/analysis/module/NamedDataServer;)V
 */
JNIEXPORT void JNICALL Java_anl_teva_analysis_module_ExternalIntermediateAnalysisServerImpl_shutdown
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     anl_teva_analysis_module_ExternalIntermediateAnalysisServerImpl
 * Method:    newSimulationResults
 * Signature: (Lanl/teva/analysis/module/NamedDataServer;Lanl/teva/analysis/module/NamedDataServer;Lanl/teva/analysis/module/NamedData;)V
 */
JNIEXPORT void JNICALL Java_anl_teva_analysis_module_ExternalIntermediateAnalysisServerImpl_newSimulationResults
  (JNIEnv *, jobject, jint, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
